---
- name: Ensure repo cloned from github
  git:
    repo: https://github.com/amix/vimrc.git
    dest: "{{ lookup('env', 'HOME') }}/.vim_runtime"
    clone: yes
    depth: 1

- name: Ensure awesome script is executable
  file:
      dest: "{{ lookup('env', 'HOME') }}/.vim_runtime/install_awesome_vimrc.sh"
      mode: u=rwx,g=rw,o=rw

- name: Install Awesome vimrc file
  shell: "{{ lookup('env', 'HOME') }}/.vim_runtime/install_awesome_vimrc.sh"
  args:
      executable: /bin/bash
